### ISSUE TITLE
What is "pollen/world"?

### ISSUE THREAD

**Issue by kit-johnson** [fasiha/pollen-guide#1]
I'm not used to github so I don't know if this is the appropriate way to ask a question.

In Take two, line two of the file is:

`◊(require pollen/world pollen/decode)`

However I don't know what that package is, or where I can install it from. It's not listed at the [racket package list](https://pkgs.racket-lang.org/#), as far as I can see.

**Comment by kit-johnson** [comment]
I might have found the problem. In the 19.4.2 [version notes ](https://docs.racket-lang.org/pollen/version-notes.html)it says

> pollen/setup replaces pollen/world

So when I change line two to be:

`◊(require pollen/setup pollen/decode)`

Then Take two will build…nearly. I now get an error:

`rendering: /take2.html.pm as /take2.html
splice: arity mismatch;
 the expected number of arguments does not match the given number
  expected: 1
  given: 2
  arguments...:
   '((h1 "Take Two. Or, some things are harder than they appear.") "\n" "\n" (section "Tufte CSS' has nice sidenotes, but ea...
   '@`

I just downloaded the file and haven't changed it except for Line Two, as described.

I'm completely new to Pollen and Racket, but from what I've seen I would really realy like to get it to work.

**Comment by fasiha** [comment]
Heya, thanks for this—this is a perfectly legit use of Github issues!

Pollen reached 1.0 after I wrote this and I haven’t fixed the things that have broken since then. Let me try and fix everything up.

**Comment by kit-johnson** [comment]
Hi Fasiha,

Great, I'm glad to hear I'm using Github OK : )

I understand if it's too much work to update this to the new version. But if you do get it done, it would be really helpful.

I'm not really a programmer. I guess learing Pollen/Racket would probably be an ideal place to start; from what I've heard it's quite a special language.

**Comment by kit-johnson** [comment]
I'm back here two years later and still struggling to make it work :-( 

What you've done in your tutorial is exactly what I was hoping to achieve…to get Tufte-style markup using Pollen.

**Comment by fasiha** [comment]
Oh no! I'm sorry, I haven't touched Pollen before it reached 1.0, and I do realize that many things have changed with it! 

I was about to ask if you'd reached out to the Pollen community via their mailing list but [I see you have](https://groups.google.com/forum/#!topic/pollenpub/3zZ_dwMbqdI)! The amazing Matthew Butterick seems to have given you some good leads, I'll monitor that thread to check your progress, I don't have time right now to get back into Racket and Pollen (though part of me thinks that I don't have time *not* to get back to Racket, and stop wasting time with crappier languages!!!).

**Comment by kit-johnson** [comment]
From what I can tell, a lot has changed since when you wrote the tutorial, so updating it would probably mean re-writing much of it from scratch. That takes time, of course. So yes, lucky me that Matthew Butterick replied… I will try what he suggested and reply when I've done that.

Thanks for your responsiveness.

**Comment by fasiha** [comment]
Thanks for the note about how much has changed—I added a big caveat at the top of my document here noting that it's hopelessly outdated.

Also, Joel Dueck uses Tufte-CSS with margin notes on his [website](https://thenotepad.org/posts/pollen-and-sqlite.html), as you can tell from their [Pollen source](https://thenotepad.org/posts/pollen-and-sqlite.pollen.html). It might be worth examining this or contacting him also for notes on how to set it up?

**Comment by andres-moreno** [comment]
How to fix the tutorial:

1. `take1` works as is. The results are not pretty because there is nothing to handle paragraphs, etc.
2. `take2` will work if one removes  `pollen/world` from the `require`. I did notice that the `Tufte css` did not work properly because of the presence of a `decode-root` tag. I think you need to replace `decode-root` with `div` in the Racket code, and also use a move recent version of `tufte.css` along with the corresponding fonts (`et-book`). Then the fonts will be right size and the page will look right.
3. `take3`: remove `pollen/world` in the `require`. Everything will work just fine. (One also needs to update the `tufte` css file and fonts as well as edit the code in `pollen.rkt` to use a `div` instead of `decode-root`)

Thanks for writing this up--I had been using `Pollen` in markdown mode but now I feel ready to move to Pollen authoring mode and to start using Tufte CSS

**Comment by fasiha** [comment]
Thanks @andres-moreno! It *sounds* like you have a working version of the tutorial with all the fixes added? If so, would you mind forking and pushing and submitting a pull request so I can merge it into this repo? I am more than willing to help with that process if you're willing but unfamiliar.

**Comment by andres-moreno** [comment]
@fasiha : will do, probably tomorrow or Saturday--I am slammed today. Thanks again for the write-up!

**Comment by fasiha** [comment]
Thanks to @andres-moreno I think we can close this! Many thanks Andres!!!
